"""Add new fields

Revision ID: 45a791c8e8ae
Revises: 4e9a942b5fcb
Create Date: 2021-04-25 07:17:48.508646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a791c8e8ae'
down_revision = '4e9a942b5fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('dosage_unit', sa.String(), nullable=False))
    op.add_column('medicines', sa.Column('frequency_unit', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'frequency_unit')
    op.drop_column('medicines', 'dosage_unit')
    # ### end Alembic commands ###
